# Generated by Django 3.0.6 on 2020-06-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(max_length=200)),
                ('sensorw', models.FloatField()),
                ('sensorh', models.FloatField()),
                ('pixelw', models.IntegerField()),
                ('pixelh', models.IntegerField()),
                ('mpixel', models.FloatField()),
                ('lensFocal', models.FloatField()),
                ('imageSize', models.FloatField()),
                ('comments', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('forward', models.IntegerField()),
                ('lateral', models.IntegerField()),
            ],
        ),
    ]
