# Generated by Django 3.0.6 on 2020-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.FloatField()),
                ('unitCost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cruiseSpeed', models.FloatField()),
                ('flightTime', models.FloatField()),
                ('pricing', models.IntegerField()),
                ('comments', models.CharField(max_length=20)),
            ],
        ),
    ]
