# Generated by Django 3.0.6 on 2020-06-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
