# Generated by Django 3.0.6 on 2020-06-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_budgetitem_drone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='comments',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
