# Generated by Django 3.0.6 on 2020-06-15 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_auto_20200615_1220'),
        ('planner', '0003_auto_20200615_1157'),
    ]

    operations = [
    ]
