# Generated by Django 3.0.6 on 2020-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_merge_20200615_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='total_cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
