# Generated by Django 3.0.6 on 2020-06-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20200624_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='days',
            field=models.FloatField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Department'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='unit',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='unitCost',
            field=models.IntegerField(null=True),
        ),
    ]
