# Generated by Django 3.0.6 on 2020-06-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_auto_20200624_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='unit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='unitCost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
