# Generated by Django 3.0.6 on 2020-07-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_auto_20200624_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Defaults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone', models.IntegerField()),
                ('camera', models.IntegerField()),
                ('surveyType', models.IntegerField()),
                ('batteryCapacity', models.IntegerField()),
                ('areaSize', models.IntegerField()),
                ('selectedMeasure', models.CharField(max_length=255)),
                ('distance_travelled_per_flight', models.FloatField()),
                ('take_of_area_distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlannerValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_flights', models.IntegerField()),
                ('orthophoto_resolution', models.FloatField()),
                ('dsm_resolution', models.FloatField()),
                ('total_number_of_images_captured', models.IntegerField()),
                ('number_of_gigapixels', models.FloatField()),
                ('total_size_of_digital_files', models.FloatField()),
                ('battery_capacity', models.IntegerField()),
                ('flight_height', models.FloatField()),
                ('take_off_area_distance', models.IntegerField()),
                ('area_size', models.IntegerField()),
                ('distance_travelled_per_flight', models.FloatField()),
                ('duration_of_mission', models.IntegerField()),
                ('camera_id', models.IntegerField()),
                ('drone_id', models.IntegerField()),
                ('survey_type_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TotalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='days',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='budgetitem',
            name='unitCost',
        ),
        migrations.CreateModel(
            name='DepartmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_Cost', models.FloatField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Department')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItemCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.FloatField()),
                ('unitCost', models.FloatField()),
                ('units', models.FloatField()),
                ('totalCost', models.FloatField()),
                ('budget_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.BudgetItem')),
            ],
        ),
    ]
