# Generated by Django 3.0.6 on 2020-07-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0011_auto_20200701_1312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalCost',
        ),
        migrations.RenameField(
            model_name='budgetestimate',
            old_name='total',
            new_name='cost',
        ),
    ]
