# Generated by Django 3.0.6 on 2020-07-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_auto_20200701_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defaults',
            new_name='Default',
        ),
        migrations.RenameModel(
            old_name='PlannerValues',
            new_name='PlannerValue',
        ),
    ]
