# Generated by Django 3.0.6 on 2020-07-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_auto_20200701_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitemcost',
            name='days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='budgetitemcost',
            name='units',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
