# Generated by Django 3.0.6 on 2020-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_auto_20200701_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetestimate',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
