# Generated by Django 3.0.6 on 2020-07-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0015_auto_20200710_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitemcost',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='budgetitemcost',
            name='unitCost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='departmentcost',
            name='total_Cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
