# Generated by Django 3.0.6 on 2020-07-13 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_auto_20200710_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannervalue',
            name='area_size',
            field=models.FloatField(),
        ),
    ]
