# Generated by Django 3.0.6 on 2020-07-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0017_auto_20200713_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannervalue',
            name='area_size',
            field=models.IntegerField(),
        ),
    ]
