# Generated by Django 3.0.6 on 2020-07-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_auto_20200713_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetestimate',
            name='name',
            field=models.CharField(default='name', max_length=40),
            preserve_default=False,
        ),
    ]
