# Generated by Django 3.0.6 on 2020-07-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0020_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannervalue',
            name='area_size_units',
            field=models.CharField(default='kilometers', max_length=50),
        ),
        migrations.AlterField(
            model_name='plannervalue',
            name='area_size',
            field=models.FloatField(default=1),
        ),
    ]
