# Generated by Django 3.0.6 on 2020-07-17 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0021_auto_20200717_0824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plannervalue',
            old_name='distance_travelled_per_flight',
            new_name='distance_travelled',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='dsm_resolution',
            new_name='dsm_reso',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='duration_of_mission',
            new_name='duration_mission',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='number_of_gigapixels',
            new_name='num_gigapixel',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='number_of_flights',
            new_name='num_images_captured',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='take_off_area_distance',
            new_name='num_of_flights',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='orthophoto_resolution',
            new_name='ortho_reso',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='area_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='total_number_of_images_captured',
            new_name='take_of_area',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='total_size_of_digital_files',
            new_name='total_digital_files',
        ),
        migrations.RenameField(
            model_name='plannervalue',
            old_name='area_size_units',
            new_name='units',
        ),
    ]
