# Generated by Django 3.0.6 on 2020-07-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0022_auto_20200717_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannervalue',
            name='size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='plannervalue',
            name='units',
            field=models.CharField(max_length=50),
        ),
    ]
