# Generated by Django 3.0.6 on 2020-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0023_auto_20200717_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannervalue',
            name='size',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plannervalue',
            name='take_of_area',
            field=models.FloatField(),
        ),
    ]
