# Generated by Django 3.0.6 on 2020-07-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0024_auto_20200717_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannervalue',
            name='area_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
