# Generated by Django 3.0.6 on 2020-07-17 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0026_areasizeandunits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaSizeAndUnits',
            new_name='AreaSizeAndUnit',
        ),
    ]
